/* Must run ONLY with driver/tests/fake_broker.py in a separate test prefix. */
typedef unsigned long U32;
typedef void *HANDLE;
typedef struct {U32 protocol,rx,tx,time,size,extra;unsigned char data[4128];} MSG;
typedef struct {U32 size;unsigned char*data;} BYTE_ARRAY;
typedef struct {U32 parameter,value;} CONFIG;
typedef struct {U32 count;CONFIG*entries;} CONFIG_LIST;
static MSG messages[3];
__declspec(dllimport) HANDLE __stdcall LoadLibraryA(const char*);
__declspec(dllimport) void* __stdcall GetProcAddress(HANDLE,const char*);
__declspec(dllimport) HANDLE __stdcall GetStdHandle(U32);
__declspec(dllimport) int __stdcall WriteFile(HANDLE,const void*,U32,U32*,void*);
__declspec(dllimport) void __stdcall ExitProcess(U32);
__declspec(dllimport) HANDLE __stdcall CreateFileA(const char*,U32,U32,void*,U32,U32,HANDLE);
__declspec(dllimport) int __stdcall CloseHandle(HANDLE);
static void text(const char*s){U32 n=0,w;while(s[n])n++;WriteFile(GetStdHandle(-11),s,n,&w,0);}
static int equal(const char*a,const char*b){while(*a&&*a==*b){a++;b++;}return *a==*b;}
#define CHECK(x) do {if(!(x)){text("FAIL: " #x "\r\n");ExitProcess(1);}}while(0)
void mainCRTStartup(void){
    HANDLE marker=CreateFileA("C:\\SIMULATION_ONLY",0x80000000,1,0,3,0x80,0);
    CHECK(marker!=(HANDLE)-1);CloseHandle(marker);
    HANDLE h=LoadLibraryA("GD101_NATIVE.dll");CHECK(h);
    U32 (__stdcall *open)(void*,U32*)=GetProcAddress(h,"PassThruOpen");
    U32 (__stdcall *close)(U32)=GetProcAddress(h,"PassThruClose");
    U32 (__stdcall *connect)(U32,U32,U32,U32,U32*)=GetProcAddress(h,"PassThruConnect");
    U32 (__stdcall *write)(U32,MSG*,U32*,U32)=GetProcAddress(h,"PassThruWriteMsgs");
    U32 (__stdcall *read)(U32,MSG*,U32*,U32)=GetProcAddress(h,"PassThruReadMsgs");
    U32 (__stdcall *error)(char*)=GetProcAddress(h,"PassThruGetLastError");
    U32 (__stdcall *disconnect)(U32)=GetProcAddress(h,"PassThruDisconnect");
    U32 (__stdcall *ioctl)(U32,U32,void*,void*)=GetProcAddress(h,"PassThruIoctl");
    U32 (__stdcall *filter)(U32,U32,MSG*,MSG*,MSG*,U32*)=GetProcAddress(h,"PassThruStartMsgFilter");
    U32 (__stdcall *stopfilter)(U32,U32)=GetProcAddress(h,"PassThruStopMsgFilter");
    CHECK(open&&close&&connect&&write&&read&&error&&disconnect&&ioctl&&filter&&stopfilter);
    U32 (__stdcall *voltage_off)(U32,U32,U32)=GetProcAddress(h,"PassThruSetProgrammingVoltage");
    CHECK(voltage_off);
    U32 id=0,channel=0,count=0;
    CHECK(open("J2534-2:other",&id)==1&&id==0);
    CHECK(open("J2534-2:",0)==4);
    CHECK(open("J2534-1:",&id)==0);CHECK(close(id)==0);
    CHECK(open("J2534-2:",&id)==0);
    CHECK(voltage_off(id,9,0xffffffff)==0);
    CHECK(voltage_off(id,12,0xffffffff)==0);
    CHECK(voltage_off(id,13,0xffffffff)==0);
    CHECK(voltage_off(id,9,12000)==19);
    CHECK(voltage_off(id,7,0xffffffff)==19);
    CHECK(voltage_off(id+100,9,0xffffffff)==26);
    CHECK(voltage_off(id,12,0xfffffffe)==19);
    CHECK(voltage_off(id,9,0xfffffffe)==0);
    CHECK(voltage_off(id,12,12000)==0);
    CHECK(voltage_off(id,13,18000)==0);
    CHECK(voltage_off(id,12,12345)==9);
    char pin_error[80];CHECK(error(pin_error)==0);
    CHECK(equal(pin_error,"Programming-pin control timed out"));
    U32 (__stdcall *version)(U32,char*,char*,char*)=GetProcAddress(h,"PassThruReadVersion");
    CHECK(version);char version_buffers[3][80];
    for(U32 i=0;i<3;i++)for(U32 j=0;j<80;j++)version_buffers[i][j]='x';
    CHECK(version(id,version_buffers[0],version_buffers[1],version_buffers[2])==9);
    for(U32 i=0;i<3;i++)for(U32 j=0;j<80;j++)CHECK(version_buffers[i][j]=='x');
    CHECK(version(id,version_buffers[0],version_buffers[1],version_buffers[2])==0);
    CHECK(equal(version_buffers[0],"SN:MT000418,FW:1.14"));
    CHECK(equal(version_buffers[1],"GD101 native experimental 0.1"));
    CHECK(equal(version_buffers[2],"04.04"));
    U32 voltage[3]={0x11223344,0,0x55667788};
    CHECK(ioctl(id,3,0,voltage+1)==0&&voltage[1]==12345);
    CHECK(voltage[0]==0x11223344&&voltage[2]==0x55667788);
    CHECK(ioctl(id,3,0,0)==4);
    CHECK(ioctl(id+100,3,0,voltage+1)==26&&voltage[1]==12345);
    CHECK(connect(id,5,0,500000,&channel)==0);
    CONFIG can_rate_settings[4]={{1,250000},{3,1},{23,331},{24,276}};CONFIG_LIST can_rate_config={4,can_rate_settings};
    CHECK(ioctl(channel,2,&can_rate_config,0)==0);
    can_rate_settings[0].value=can_rate_settings[1].value=0;
    CHECK(ioctl(channel,1,&can_rate_config,0)==0);
    CHECK(can_rate_settings[0].value==250000&&can_rate_settings[1].value==1);
    CHECK(can_rate_settings[2].value==75&&can_rate_settings[3].value==20);
    can_rate_settings[0].value=123;can_rate_settings[1].value=0;
    CHECK(ioctl(channel,2,&can_rate_config,0)==10);
    CHECK(ioctl(channel,1,&can_rate_config,0)==0);
    CHECK(can_rate_settings[0].value==250000&&can_rate_settings[1].value==1);
    can_rate_settings[0].value=500000;can_rate_settings[1].value=0;
    can_rate_settings[2].value=80;can_rate_settings[3].value=15;
    CHECK(ioctl(channel,2,&can_rate_config,0)==0);
    U32 (__stdcall *periodic)(U32,MSG*,U32*,U32)=GetProcAddress(h,"PassThruStartPeriodicMsg");
    U32 (__stdcall *stopperiodic)(U32,U32)=GetProcAddress(h,"PassThruStopPeriodicMsg");
    CHECK(periodic&&stopperiodic);
    messages[0].protocol=5;messages[0].tx=0;messages[0].size=5;
    messages[0].data[0]=messages[0].data[1]=0;messages[0].data[2]=7;
    messages[0].data[3]=0xdf;messages[0].data[4]=1;
    U32 periodic_id=99;
    CHECK(periodic(channel,0,&periodic_id,1000)==4&&periodic_id==0);
    CHECK(periodic(channel,messages,&periodic_id,1000)==0&&periodic_id!=0);
    CHECK(stopperiodic(channel,periodic_id)==0);
    CHECK(stopperiodic(channel,periodic_id)==13);
    CHECK(periodic(channel,messages,&periodic_id,1000)==0);
    CHECK(ioctl(channel,9,0,0)==0);
    CHECK(stopperiodic(channel,periodic_id)==13);
    CHECK(read(channel,messages,0,0)==4);
    messages[2].size=0xaabbccdd;count=3;
    CHECK(read(channel,messages,&count,0)==0&&count==2);
    CHECK(messages[0].protocol==5&&messages[0].rx==0&&messages[0].time==1234);
    CHECK(messages[0].size==6&&messages[0].extra==6&&messages[0].data[3]==0xe8&&messages[0].data[4]==0x41);
    CHECK(messages[1].rx==0x100&&messages[1].time==0xfffffff0&&messages[1].data[0]==0x18&&messages[1].size==5);
    CHECK(messages[2].size==0xaabbccdd);
    count=2;CHECK(read(channel,messages,&count,1000)==9&&count==1);
    CHECK(messages[0].size==4&&messages[0].data[2]==1&&messages[0].data[3]==0x23);
    count=1;CHECK(read(channel,messages,&count,0)==16&&count==0);
    CHECK(write(channel,messages,0,100)==4);
    count=1;CHECK(write(channel,0,&count,100)==4&&count==0);
    messages[0].protocol=messages[1].protocol=5;
    messages[0].size=messages[1].size=5;
    messages[0].data[0]=messages[0].data[1]=messages[1].data[0]=messages[1].data[1]=0;
    messages[0].data[2]=messages[1].data[2]=7;
    messages[0].data[3]=messages[1].data[3]=0xdf;
    messages[0].data[4]=0x11;messages[1].data[4]=0x22;
    count=2;CHECK(write(channel,messages,&count,0)==17&&count==1);
    CHECK(ioctl(channel,7,0,0)==0);
    messages[0].size=13;count=1;CHECK(write(channel,messages,&count,100)==10&&count==0);
    messages[0].size=5;
    CONFIG can_loopback={3,0};CONFIG_LIST can_loopback_config={1,&can_loopback};
    CHECK(ioctl(channel,1,&can_loopback_config,0)==0&&can_loopback.value==0);
    can_loopback.value=7;
    CHECK(ioctl(channel,2,&can_loopback_config,0)==0);
    can_loopback.value=0;
    CHECK(ioctl(channel,1,&can_loopback_config,0)==0&&can_loopback.value==1);
    count=2;CHECK(write(channel,messages,&count,1000)==9&&count==1);
    char description[80];CHECK(error(description)==0);
    CHECK(description[0]=='C'&&description[1]=='A'&&description[2]=='N');
    count=1;CHECK(read(channel,messages+2,&count,0)==0&&count==1);
    CHECK(messages[2].protocol==5&&messages[2].rx==1&&messages[2].time==43210);
    CHECK(messages[2].size==5&&messages[2].extra==5);
    CHECK(messages[2].data[0]==0&&messages[2].data[1]==0&&messages[2].data[2]==7);
    CHECK(messages[2].data[3]==0xdf&&messages[2].data[4]==0x11);
    count=1;CHECK(read(channel,messages+2,&count,0)==16&&count==0);
    /* Simulator latched an uncertain second write; a third is not transmitted. */
    count=1;CHECK(write(channel,messages,&count,100)==7&&count==0);
    CHECK(disconnect(channel)==0);
    CHECK(connect(id,4,0x200,10400,&channel)==0);
    CONFIG kline_rate={1,9600};CONFIG_LIST kline_rate_config={1,&kline_rate};
    CHECK(ioctl(channel,2,&kline_rate_config,0)==0);
    kline_rate.value=0;CHECK(ioctl(channel,1,&kline_rate_config,0)==0&&kline_rate.value==9600);
    kline_rate.value=123;CHECK(ioctl(channel,2,&kline_rate_config,0)==10);
    CHECK(ioctl(channel,1,&kline_rate_config,0)==0&&kline_rate.value==9600);
    kline_rate.value=10400;CHECK(ioctl(channel,2,&kline_rate_config,0)==0);
    CONFIG parity_setting={22,0x102};CONFIG_LIST parity_config={1,&parity_setting};
    CHECK(ioctl(channel,2,&parity_config,0)==0);
    parity_setting.value=0;CHECK(ioctl(channel,1,&parity_config,0)==0&&parity_setting.value==2);
    parity_setting.value=3;CHECK(ioctl(channel,2,&parity_config,0)==10);
    CHECK(ioctl(channel,1,&parity_config,0)==0&&parity_setting.value==2);
    parity_setting.value=0;CHECK(ioctl(channel,2,&parity_config,0)==0);
    CONFIG data_bits={32,99};CONFIG_LIST data_bits_config={1,&data_bits};
    CHECK(ioctl(channel,1,&data_bits_config,0)==0&&data_bits.value==0);
    data_bits.value=1;CHECK(ioctl(channel,2,&data_bits_config,0)==10);
    CHECK(ioctl(channel,1,&data_bits_config,0)==0&&data_bits.value==0);
    data_bits.value=0x100;CHECK(ioctl(channel,2,&data_bits_config,0)==0);
    CHECK(ioctl(channel,1,&data_bits_config,0)==0&&data_bits.value==0);



    messages[0].protocol=4;messages[0].tx=0;messages[0].size=1;messages[0].data[0]=0x81;
    count=1;CHECK(write(channel,messages,&count,0)==0&&count==1);
    CHECK(ioctl(channel,7,0,0)==0);
    CHECK(periodic(channel,messages,&periodic_id,99)==10);
    CHECK(periodic(channel,messages,&periodic_id,1000)==0);
    CHECK(stopperiodic(channel,periodic_id)==0);
    CHECK(periodic(channel,messages,&periodic_id,1000)==0);
    CHECK(ioctl(channel,9,0,0)==0);
    CHECK(stopperiodic(channel,periodic_id)==13);
    U32 pass=0,block=0;
    messages[0].protocol=messages[1].protocol=4;
    messages[0].tx=messages[1].tx=0;messages[0].size=messages[1].size=0;
    CHECK(filter(channel,1,&messages[0],&messages[1],0,&pass)==0&&pass);
    messages[0].size=messages[1].size=1;messages[0].data[0]=0xff;messages[1].data[0]=0x81;
    CHECK(filter(channel,2,&messages[0],&messages[1],0,&block)==0&&block!=pass);
    count=1;messages[1].size=0xaabbccdd;
    CHECK(read(channel,messages,&count,0)==0&&count==1);
    CHECK(messages[0].protocol==4&&messages[0].size==512&&messages[0].extra==512);
    CHECK(messages[0].time==2000&&messages[0].data[0]==0x82&&messages[0].data[511]==0x82);
    CHECK(messages[1].size==0xaabbccdd);
    CHECK(ioctl(channel,8,0,0)==0);
    count=1;CHECK(read(channel,messages,&count,0)==16&&count==0);
    CHECK(stopfilter(channel,block)==0);CHECK(stopfilter(channel,block)==22);
    CHECK(ioctl(channel,10,0,0)==0);CHECK(stopfilter(channel,pass)==22);
    count=1;CHECK(read(channel,messages,&count,100)==9&&count==0);
    unsigned char address=0x33,keywords[4]={0xaa,0xbb,0xcc,0xdd};
    BYTE_ARRAY init_in={1,&address},init_out={1,keywords};
    CHECK(ioctl(channel,4,0,&init_out)==4);
    CHECK(ioctl(channel,4,&init_in,0)==4);
    CHECK(ioctl(channel,4,&init_in,&init_out)==18);
    init_out.size=4;init_in.size=2;
    CHECK(ioctl(channel,4,&init_in,&init_out)==10);
    CHECK(keywords[0]==0xaa&&keywords[1]==0xbb&&init_out.size==4);
    init_in.size=1;CHECK(ioctl(channel,4,&init_in,&init_out)==0);
    CHECK(init_out.size==2&&keywords[0]==8&&keywords[1]==8&&keywords[2]==0xcc&&keywords[3]==0xdd);
    CHECK(address==0x33);
    kline_rate.value=0;CHECK(ioctl(channel,1,&kline_rate_config,0)==0&&kline_rate.value==9600);
    address=0x34;init_out.size=4;CHECK(ioctl(channel,4,&init_in,&init_out)==9);
    CHECK(init_out.size==4&&keywords[0]==8&&keywords[1]==8&&keywords[2]==0xcc&&keywords[3]==0xdd);
    messages[0].protocol=4;messages[0].tx=0;messages[0].size=5;
    messages[0].data[0]=0xc1;messages[0].data[1]=0x33;messages[0].data[2]=0xf1;
    messages[0].data[3]=0x81;messages[0].data[4]=0x66;
    CHECK(ioctl(channel,5,messages,&messages[1])==0);
    CHECK(messages[1].protocol==4&&messages[1].time==4321&&messages[1].size==512);
    CHECK(messages[1].extra==512&&messages[1].data[255]==255&&messages[1].data[511]==255);
    CHECK(ioctl(channel,5,messages,0)==0);
    messages[0].size=229;CHECK(ioctl(channel,5,messages,&messages[1])==10);
    messages[0].size=1;messages[0].data[0]=0x81;messages[1].size=0xaabbccdd;
    CHECK(ioctl(channel,5,messages,&messages[1])==9);
    CHECK(messages[1].size==0xaabbccdd);
    CONFIG kline_loopback={3,0};CONFIG_LIST kline_loopback_config={1,&kline_loopback};
    CHECK(ioctl(channel,1,&kline_loopback_config,0)==0&&kline_loopback.value==0);
    kline_loopback.value=0x102;
    CHECK(ioctl(channel,2,&kline_loopback_config,0)==10);
    CHECK(ioctl(channel,1,&kline_loopback_config,0)==0&&kline_loopback.value==0);
    kline_loopback.value=0x101;
    CHECK(ioctl(channel,2,&kline_loopback_config,0)==0);
    kline_loopback.value=0;
    CHECK(ioctl(channel,1,&kline_loopback_config,0)==0&&kline_loopback.value==1);
    messages[0].size=512;
    for(U32 j=0;j<512;j++)messages[0].data[j]=(unsigned char)j;
    count=1;CHECK(write(channel,messages,&count,1000)==0&&count==1);
    count=1;CHECK(read(channel,messages+2,&count,0)==0&&count==1);
    CHECK(messages[2].protocol==4&&messages[2].rx==1&&messages[2].time==67890);
    CHECK(messages[2].size==512&&messages[2].extra==512);
    for(U32 j=0;j<512;j++)CHECK(messages[2].data[j]==(unsigned char)j);
    messages[0].size=4096;
    for(U32 j=0;j<4096;j++)messages[0].data[j]=(unsigned char)j;
    count=1;CHECK(write(channel,messages,&count,1000)==0&&count==1);
    count=1;CHECK(read(channel,messages+2,&count,0)==0&&count==1);
    CHECK(messages[2].rx==1&&messages[2].size==4096&&messages[2].extra==4096);
    for(U32 j=0;j<4096;j++)CHECK(messages[2].data[j]==(unsigned char)j);
    messages[0].size=1;messages[0].data[0]=0x81;
    count=1;CHECK(write(channel,messages,&count,1000)==9&&count==0);
    count=1;CHECK(read(channel,messages+2,&count,0)==16&&count==0);
    CONFIG settings[5]={{10,80},{12,2},{19,30},{20,70},{21,210}};
    CONFIG_LIST configs={5,settings};
    CHECK(ioctl(channel,2,&configs,0)==0);
    for(U32 i=0;i<5;i++)settings[i].value=0;
    CHECK(ioctl(channel,1,&configs,0)==0);
    CHECK(settings[0].value==80&&settings[1].value==2&&settings[2].value==30&&settings[3].value==70&&settings[4].value==210);
    CONFIG receive_gap={7,8};CONFIG_LIST gap_config={1,&receive_gap};
    CHECK(ioctl(channel,2,&gap_config,0)==0);
    receive_gap.value=0;CHECK(ioctl(channel,1,&gap_config,0)==0&&receive_gap.value==8);
    CONFIG handshake[6]={{25,401},{14,402},{15,11},{16,12},{17,13},{33,2}};
    CONFIG_LIST handshake_config={6,handshake};
    CHECK(ioctl(channel,2,&handshake_config,0)==0);
    for(U32 i=0;i<6;i++)handshake[i].value=0;
    CHECK(ioctl(channel,1,&handshake_config,0)==0);
    CHECK(handshake[0].value==401&&handshake[1].value==402&&handshake[2].value==11&&handshake[3].value==12&&handshake[4].value==13&&handshake[5].value==2);
    handshake[0].parameter=18;CHECK(ioctl(channel,2,&handshake_config,0)==1);
    settings[4].parameter=99;settings[0].value=123;
    CHECK(ioctl(channel,1,&configs,0)==1&&settings[0].value==123);
    configs.count=65;CHECK(ioctl(channel,2,&configs,0)==10);
    configs.count=1;configs.entries=0;CHECK(ioctl(channel,2,&configs,0)==4);
    CHECK(disconnect(channel)==0);
    CHECK(connect(id,6,0,500000,&channel)==0);
    CONFIG rate_settings[2]={{1,0},{3,99}};CONFIG_LIST rate_config={2,rate_settings};
    CHECK(ioctl(channel,1,&rate_config,0)==0);
    CHECK(rate_settings[0].value==500000&&rate_settings[1].value==0);
    CONFIG loopback={3,0};CONFIG_LIST loopback_config={1,&loopback};
    CHECK(ioctl(channel,1,&loopback_config,0)==0&&loopback.value==0);
    loopback.value=0xffffffff;
    CHECK(ioctl(channel,2,&loopback_config,0)==0);
    loopback.value=0;
    CHECK(ioctl(channel,1,&loopback_config,0)==0&&loopback.value==1);
    CONFIG iso_settings[3]={{30,8},{31,0xf1},{43,0xaa}};
    CONFIG_LIST iso_config={3,iso_settings};
    CHECK(ioctl(channel,2,&iso_config,0)==0);
    for(U32 i=0;i<3;i++)iso_settings[i].value=0;
    CHECK(ioctl(channel,1,&iso_config,0)==0);
    CHECK(iso_settings[0].value==8&&iso_settings[1].value==0xf1&&iso_settings[2].value==0xaa);
    CONFIG iso_words[5]={{34,0x1234},{35,0x5678},{37,9},{46,0x2345},{49,0x6789}};
    CONFIG_LIST iso_word_config={5,iso_words};
    CHECK(ioctl(channel,2,&iso_word_config,0)==0);
    for(U32 i=0;i<5;i++)iso_words[i].value=0;
    CHECK(ioctl(channel,1,&iso_word_config,0)==0);
    CHECK(iso_words[0].value==0x1234&&iso_words[1].value==0x5678&&iso_words[2].value==9&&iso_words[3].value==0x2345&&iso_words[4].value==0x6789);
    for(U32 i=0;i<3;i++){messages[i].protocol=6;messages[i].tx=0;messages[i].size=4;}
    for(U32 i=0;i<4;i++){messages[0].data[i]=255;messages[1].data[i]=messages[2].data[i]=0;}
    messages[1].data[2]=messages[2].data[2]=7;messages[1].data[3]=0xe8;messages[2].data[3]=0xe0;
    U32 flow_handle=0;
    CHECK(filter(channel,3,messages,messages+1,messages+2,&flow_handle)==0);
    CONFIG iso_rate_items[3]={{1,250000},{30,9},{3,1}};CONFIG_LIST iso_rate_config={3,iso_rate_items};
    CHECK(ioctl(channel,2,&iso_rate_config,0)==0);
    for(U32 i=0;i<3;i++)iso_rate_items[i].value=0;
    CHECK(ioctl(channel,1,&iso_rate_config,0)==0);
    CHECK(iso_rate_items[0].value==250000&&iso_rate_items[1].value==9&&iso_rate_items[2].value==1);
    iso_rate_items[0].value=123;iso_rate_items[1].value=10;
    CHECK(ioctl(channel,2,&iso_rate_config,0)==10);
    CHECK(ioctl(channel,1,&iso_rate_config,0)==0);
    CHECK(iso_rate_items[0].value==250000&&iso_rate_items[1].value==9);

    messages[0].protocol=6;messages[0].tx=0;messages[0].size=516;
    messages[0].data[0]=messages[0].data[1]=0;messages[0].data[2]=7;messages[0].data[3]=0xe0;
    for(U32 i=0;i<512;i++)messages[0].data[4+i]=(unsigned char)i;
    count=1;CHECK(write(channel,messages,&count,0)==0&&count==1);
    CHECK(ioctl(channel,7,0,0)==0);
    /* Earlier config test changed parameter49; restore periodic minimum. */
    CONFIG periodic_minimum={49,1000};CONFIG_LIST minimum_config={1,&periodic_minimum};
    CHECK(ioctl(channel,2,&minimum_config,0)==0);
    CHECK(periodic(channel,messages,&periodic_id,999)==10&&periodic_id==0);
    CHECK(periodic(channel,messages,&periodic_id,1000)==0);
    CHECK(stopperiodic(channel,periodic_id)==0);
    CHECK(periodic(channel,messages,&periodic_id,1000)==0);
    CHECK(ioctl(channel,9,0,0)==0);
    CHECK(stopperiodic(channel,periodic_id)==13);
    count=1;CHECK(write(channel,messages,&count,1000)==0&&count==1);
    count=1;CHECK(read(channel,messages+1,&count,0)==0&&count==1);
    CHECK(messages[1].protocol==6&&messages[1].rx==2&&messages[1].size==4&&messages[1].time==900);
    count=1;CHECK(read(channel,messages,&count,0)==0&&count==1);
    CHECK(messages[0].protocol==6&&messages[0].size==516&&messages[0].time==999);
    CHECK(messages[0].data[3]==0xe8&&messages[0].data[515]==255);
    count=1;CHECK(read(channel,messages+1,&count,0)==0&&count==1);
    CHECK(messages[1].protocol==6&&messages[1].rx==9&&messages[1].size==4&&messages[1].time==1001);
    CHECK(messages[1].data[2]==7&&messages[1].data[3]==0xe0);
    count=1;CHECK(read(channel,messages+1,&count,0)==0&&count==1);
    CHECK(messages[1].protocol==6&&messages[1].rx==1&&messages[1].size==516&&messages[1].time==1001);
    CHECK(messages[1].extra==516);
    CHECK(messages[1].data[0]==0&&messages[1].data[1]==0&&messages[1].data[2]==7&&messages[1].data[3]==0xe0);
    for(U32 i=0;i<512;i++)CHECK(messages[1].data[4+i]==(unsigned char)i);
    messages[2].protocol=99;count=1;
    CHECK(read(channel,messages+2,&count,0)==18&&count==0&&messages[2].protocol==99);
    CHECK(stopfilter(channel,flow_handle)==0);
    CHECK(stopfilter(channel,flow_handle)==22);
    count=1;CHECK(write(channel,messages,&count,1000)==23&&count==0);
    CHECK(ioctl(channel,10,0,0)==0);
    CHECK(disconnect(channel)==0);
    CHECK(close(id)==0);
    text("PASS: Windows DLL CAN reads/writes and K-line FAST_INIT, validation, timestamps, partial counts, timeout and no retry. SIMULATED adapter only.\r\n");
    ExitProcess(0);
}
